#!/bin/bash
# cp src/myStyle.elm.example src/myStyle.elm
npx elm-live src/StyleGuide.elm --start-page=style-guide.html --dir=docs --path-to-elm=node_modules/.bin/elm --port=8002 -- --debug --output=docs/js-dev/style-guide.js
